// Generated by drift_dev when running `build_runner build`
import 'package:drift/drift.dart';

import 'connection/connection.dart' as impl;
import 'tables.dart';

part 'database.g.dart';

@DriftDatabase(tables: [LogEntries])
class LogDataBase extends _$LogDataBase {
  LogDataBase() : super(impl.connect());

  @override
  int get schemaVersion => 1;
}
