name: myapp
description: A new nice flutter project
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  beamer: ^1.5.3
  cupertino_icons: ^1.0.2
  device_info_plus: ^8.0.0
  # drift to store the data persistence in locally db
  # https://drift.simonbinder.eu/
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  # how the localisation works
  # https://docs.flutter.dev/development/accessibility-and-localization/internationalization#adding-your-own-localized-messages
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.17
  formz: ^0.6.0
  intl: any
  logging: ^1.1.1
  package_info_plus: ^3.0.2
  repositories:
    path: packages/repositories
dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

# just change the logo and the color maybe
# and the run flutter pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/images/logo.png
  color: "#FFFFFF"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - .env
    - fonts/clicker-script/
  # here you can add just new fonts if you want
  # keep in mind to add the license to the app, for all stuff it doesn't come from pub.dev
  # how to add the license to app, just see app.dart
  fonts:
    - family: Clicker Script
      fonts:
        - asset: fonts/clicker-script/ClickerScript-Regular.ttf
          weight: 400
